AWSTemplateFormatVersion: '2025-08-20'
Transform: AWS::Serverless-2016-10-31
Description: Lambda calling GraphQL API (Node.js 20)

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: nodejs20.x

Resources:
  # Lambda that calls the GraphQL API
  GraphQLCallerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/graphqlCaller.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          GRAPHQL_API_URL: "https://u6ptuvsgprc75bwvvsrewqikty.appsync-api.us-west-1.amazonaws.com/graphql"  #GraphQL endpoint
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - execute-api:Invoke
            Resource: "*"

Outputs:
  LambdaName:
    Value: !Ref GraphQLCallerFunction
    Description: Lambda that calls GraphQL API
